INSERT INTO airports (name, country_code, iata_code) VALUES ('Aalborg Airport', 'DK', 'AAL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Aji Pangeran Tumenggung Pranoto International Airport', 'ID', 'AAP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Albuquerque International Sunport', 'US', 'ABQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nnamdi Azikiwe International Airport', 'NG', 'ABV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Aberdeen Dyce Airport', 'GB', 'ABZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Juan N Alvarez International Airport', 'MX', 'ACA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kotoka International Airport', 'GH', 'ACC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('California Redwood Coast-Humboldt County International Airport', 'US', 'ACV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Adana ≈ûakirpa≈üa Airport', 'TR', 'ADA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Adnan Menderes International Airport', 'TR', 'ADB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Addis Ababa Bole International Airport', 'ET', 'ADD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Adelaide International Airport', 'AU', 'ADL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Joint Base Andrews', 'US', 'ADW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sochi International Airport', 'RU', 'AER');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fort Worth Alliance Airport', 'US', 'AFW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('M√°laga Airport', 'ES', 'AGP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Augusta Regional At Bush Field', 'US', 'AGS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Auckland International Airport', 'NZ', 'AKL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('RAF Akrotiri', 'GB', 'AKT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Almaty Airport', 'KZ', 'ALA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Alicante International Airport', 'ES', 'ALC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Houari Boumediene Airport', 'DZ', 'ALG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Aleppo International Airport', 'SY', 'ALP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rick Husband Amarillo International Airport', 'US', 'AMA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Queen Alia International Airport', 'JO', 'AMM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Amsterdam Airport Schiphol', 'NL', 'AMS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ted Stevens Anchorage International Airport', 'US', 'ANC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Stockholm-Arlanda Airport', 'SE', 'ARN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ashgabat International Airport', 'TM', 'ASB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Eleftherios Venizelos International Airport', 'GR', 'ATH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hartsfield Jackson Atlanta International Airport', 'US', 'ATL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sri Guru Ram Dass Jee International Airport', 'IN', 'ATQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Queen Beatrix International Airport', 'AW', 'AUA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Abu Dhabi International Airport', 'AE', 'AUH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Austin Bergstrom International Airport', 'US', 'AUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Asheville Regional Airport', 'US', 'AVL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Antalya International Airport', 'TR', 'AYT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Beale Air Force Base', 'US', 'BAB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Barksdale Air Force Base', 'US', 'BAD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bahrain International Airport', 'BH', 'BAH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Barcelona International Airport', 'ES', 'BCN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bradley International Airport', 'US', 'BDL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Belgrade Nikola Tesla Airport', 'RS', 'BEG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Val de Cans/J√∫lio Cezar Ribeiro International Airport', 'BR', 'BEL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Berlin Brandenburg Airport', 'DE', 'BER');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Beirut Rafic Hariri International Airport', 'LB', 'BEY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Boeing Field King County International Airport', 'US', 'BFI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Belfast International Airport', 'GB', 'BFS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bergen Airport Flesland', 'NO', 'BGO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bangor International Airport', 'US', 'BGR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Baghdad International Airport / New Al Muthana Air Base', 'IQ', 'BGW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Milan Bergamo Airport', 'IT', 'BGY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('George Best Belfast City Airport', 'GB', 'BHD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Birmingham-Shuttlesworth International Airport', 'US', 'BHM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Birmingham International Airport', 'GB', 'BHX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Billings Logan International Airport', 'US', 'BIL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Soummam ‚Äì Abane Ramdane Airport', 'DZ', 'BJA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Milas Bodrum International Airport', 'TR', 'BJV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Suvarnabhumi Airport', 'TH', 'BKK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Modibo Keita International Airport', 'ML', 'BKO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Jos√© Antonio Anzoategui International Airport', 'VE', 'BLA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Boulder City-Lake Mead International Airport', 'US', 'BLD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Billund Airport', 'DK', 'BLL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bologna Guglielmo Marconi Airport', 'IT', 'BLQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kempegowda International Airport', 'IN', 'BLR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Scott AFB/Midamerica Airport', 'US', 'BLV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Central Illinois Regional Airport at Bloomington-Normal', 'US', 'BMI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nashville International Airport', 'US', 'BNA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Brisbane International Airport', 'AU', 'BNE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bordeaux-M√©rignac Airport', 'FR', 'BOD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('El Dorado International Airport', 'CO', 'BOG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bournemouth Airport', 'GB', 'BOH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Boise Air Terminal/Gowen Field', 'US', 'BOI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Burgas Airport', 'BG', 'BOJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chhatrapati Shivaji International Airport', 'IN', 'BOM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Flamingo International Airport', 'BQ', 'BON');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bod√∏ Airport', 'NO', 'BOO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Logan International Airport', 'US', 'BOS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bremen Airport', 'DE', 'BRE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bari Karol Wojty≈Ça Airport', 'IT', 'BRI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bristol Airport', 'GB', 'BRS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Brussels Airport', 'BE', 'BRU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Presidente Juscelino Kubitschek International Airport', 'BR', 'BSB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('EuroAirport Basel-Mulhouse-Freiburg Airport', 'FR', 'BSL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Basra International Airport', 'IQ', 'BSR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('M. R. ≈†tef√°nik Airport', 'SK', 'BTS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Budapest Liszt Ferenc International Airport', 'HU', 'BUD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Buffalo Niagara International Airport', 'US', 'BUF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Baltimore/Washington International Thurgood Marshall Airport', 'US', 'BWI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Brunei International Airport', 'BN', 'BWN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Philip S. W. Goldson International Airport', 'BZ', 'BZE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bydgoszcz Ignacy Jan Paderewski Airport', 'PL', 'BZG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('RAF Brize Norton', 'GB', 'BZZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Columbia Metropolitan Airport', 'US', 'CAE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cagliari Elmas Airport', 'IT', 'CAG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cairo International Airport', 'EG', 'CAI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Guangzhou Baiyun International Airport', 'CN', 'CAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Columbus Air Force Base', 'US', 'CBM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Canberra International Airport', 'AU', 'CBR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Calicut International Airport', 'IN', 'CCJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sim√≥n Bol√≠var International Airport', 'VE', 'CCS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Netaji Subhash Chandra Bose International Airport', 'IN', 'CCU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Charles de Gaulle International Airport', 'FR', 'CDG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mactan Cebu International Airport', 'PH', 'CEB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Congonhas Airport', 'BR', 'CGH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Soekarno-Hatta International Airport', 'ID', 'CGK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cologne Bonn Airport', 'DE', 'CGN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Zhengzhou Xinzheng International Airport', 'CN', 'CGO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Laguindingan Airport', 'PH', 'CGY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chattanooga Metropolitan Airport (Lovell Field)', 'US', 'CHA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Christchurch International Airport', 'NZ', 'CHC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Charleston International Airport', 'US', 'CHS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ciampino‚ÄìG. B. Pastine International Airport', 'IT', 'CIA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('The Eastern Iowa Airport', 'US', 'CID');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cheongju International Airport/Cheongju Air Base (K-59/G-513)', 'KR', 'CJJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jeju International Airport', 'KR', 'CJU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chongqing Jiangbei International Airport', 'CN', 'CKG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cleveland Hopkins International Airport', 'US', 'CLE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Charlotte Douglas International Airport', 'US', 'CLT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bandaranaike International Colombo Airport', 'LK', 'CMB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('John Glenn Columbus International Airport', 'US', 'CMH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mohammed V International Airport', 'MA', 'CMN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tancredo Neves International Airport', 'BR', 'CNF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chiang Mai International Airport', 'TH', 'CNX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cochin International Airport', 'IN', 'COK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('City of Colorado Springs Municipal Airport', 'US', 'COS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Copenhagen Kastrup Airport', 'DK', 'CPH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cape Town International Airport', 'ZA', 'CPT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Diosdado Macapagal International Airport', 'PH', 'CRK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Brussels South Charleroi Airport', 'BE', 'CRL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Corpus Christi International Airport', 'US', 'CRP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yeager Airport', 'US', 'CRW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Changsha Huanghua International Airport', 'CN', 'CSX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Catania-Fontanarossa Airport', 'IT', 'CTA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('New Chitose Airport', 'JP', 'CTS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chengdu Shuangliu International Airport', 'CN', 'CTU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bachigualato Federal International Airport', 'MX', 'CUL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Canc√∫n International Airport', 'MX', 'CUN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hato International Airport', 'CW', 'CUR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Alejandro Velasco Astete International Airport', 'PE', 'CUZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cincinnati Northern Kentucky International Airport', 'US', 'CVG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cannon Air Force Base', 'US', 'CVS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Afonso Pena Airport', 'BR', 'CWB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cardiff International Airport', 'GB', 'CWL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Daytona Beach International Airport', 'US', 'DAB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hazrat Shahjalal International Airport', 'BD', 'DAC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Da Nang International Airport', 'VN', 'DAD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dallas Love Field', 'US', 'DAL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Damascus International Airport', 'SY', 'DAM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Julius Nyerere International Airport', 'TZ', 'DAR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('James M Cox Dayton International Airport', 'US', 'DAY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dubuque Regional Airport', 'US', 'DBQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ronald Reagan Washington National Airport', 'US', 'DCA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Indira Gandhi International Airport', 'IN', 'DEL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Denver International Airport', 'US', 'DEN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dallas Fort Worth International Airport', 'US', 'DFW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Abdulaziz Air Base', 'SA', 'DHA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sentani International Airport', 'ID', 'DJJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dalian Zhoushuizi International Airport', 'CN', 'DLC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Laughlin Air Force Base', 'US', 'DLF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Duluth International Airport', 'US', 'DLH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dalaman International Airport', 'TR', 'DLM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Domodedovo International Airport', 'RU', 'DME');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Don Mueang International Airport', 'TH', 'DMK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Fahd International Airport', 'SA', 'DMM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kadena Air Base', 'JP', 'DNA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hamad International Airport', 'QA', 'DOH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dover Air Force Base', 'US', 'DOV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ngurah Rai (Bali) International Airport', 'ID', 'DPS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Duqm International Airport', 'OM', 'DQM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dresden Airport', 'DE', 'DRS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Robin Hood Doncaster Sheffield Airport', 'GB', 'DSA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Des Moines International Airport', 'US', 'DSM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Blaise Diagne International Airport', 'SN', 'DSS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dortmund Airport', 'DE', 'DTM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Detroit Metropolitan Wayne County Airport', 'US', 'DTW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dublin Airport', 'IE', 'DUB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Shaka International Airport', 'ZA', 'DUR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('D√ºsseldorf Airport', 'DE', 'DUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Francisco Bangoy International Airport', 'PH', 'DVO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Al Maktoum International Airport', 'AE', 'DWC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dubai International Airport', 'AE', 'DXB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dyess Air Force Base', 'US', 'DYS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Entebbe International Airport', 'UG', 'EBB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Edinburgh Airport', 'GB', 'EDI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Edwards Air Force Base', 'US', 'EDW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Eindhoven Airport', 'NL', 'EIN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('East Midlands Airport', 'GB', 'EMA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vance Air Force Base', 'US', 'END');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Erie International Tom Ridge Field', 'US', 'ERI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Erzurum International Airport', 'TR', 'ERZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Esenboƒüa International Airport', 'TR', 'ESB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ramon Airport', 'IL', 'ETM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Zvartnots International Airport', 'AM', 'EVN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Newark Liberty International Airport', 'US', 'EWR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Exeter International Airport', 'GB', 'EXT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Key West International Airport', 'US', 'EYW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ministro Pistarini International Airport', 'AR', 'EZE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fairbanks International Airport', 'US', 'FAI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Faro Airport', 'PT', 'FAO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fresno Yosemite International Airport', 'US', 'FAT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Leonardo da Vinci‚ÄìFiumicino Airport', 'IT', 'FCO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('RAF Fairford', 'GB', 'FFD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Wright-Patterson Air Force Base', 'US', 'FFO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ndjili International Airport', 'CD', 'FIH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Karlsruhe Baden-Baden Airport', 'DE', 'FKB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Flagstaff Pulliam International Airport', 'US', 'FLG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fort Lauderdale Hollywood International Airport', 'US', 'FLL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Herc√≠lio Luz International Airport', 'BR', 'FLN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('M√ºnster Osnabr√ºck Airport', 'DE', 'FMO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lungi International Airport', 'SL', 'FNA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fuzhou Changle International Airport', 'CN', 'FOC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Frankfurt am Main Airport', 'DE', 'FRA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Manas International Airport', 'KG', 'FRU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fort Smith Regional Airport', 'US', 'FSM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mount Fuji Shizuoka Airport', 'JP', 'FSZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fort Worth Meacham International Airport', 'US', 'FTW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fukuoka Airport', 'JP', 'FUK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fort Wayne International Airport', 'US', 'FWA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sir Seretse Khama International Airport', 'BW', 'GBE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Owen Roberts International Airport', 'KY', 'GCM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Don Miguel Hidalgo Y Costilla International Airport', 'MX', 'GDL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gda≈Ñsk Lech Wa≈Çƒôsa Airport', 'PL', 'GDN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Noum√©a Magenta Airport', 'NC', 'GEA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Spokane International Airport', 'US', 'GEG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rio Gale√£o ‚Äì Tom Jobim International Airport', 'BR', 'GIG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Glasgow International Airport', 'GB', 'GLA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gimpo International Airport', 'KR', 'GMP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Genoa Cristoforo Colombo Airport', 'IT', 'GOA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dabolim Airport', 'IN', 'GOI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gothenburg-Landvetter Airport', 'SE', 'GOT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gulfport Biloxi International Airport', 'US', 'GPT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Austin Straubel International Airport', 'US', 'GRB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('George Airport', 'ZA', 'GRJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Guarulhos - Governador Andr√© Franco Montoro International Airport', 'BR', 'GRU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Grozny North Airport', 'RU', 'GRV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Seymour Johnson Air Force Base', 'US', 'GSB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Piedmont Triad International Airport', 'US', 'GSO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Greenville Spartanburg International Airport', 'US', 'GSP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gagarin International Airport', 'RU', 'GSV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('La Aurora Airport', 'GT', 'GUA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Antonio B. Won Pat International Airport', 'GU', 'GUM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Grissom Air Reserve Base', 'US', 'GUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Geneva Cointrin International Airport', 'CH', 'GVA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Heydar Aliyev International Airport', 'AZ', 'GYD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gaziantep International Airport', 'TR', 'GZT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hannover Airport', 'DE', 'HAJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Haikou Meilan International Airport', 'CN', 'HAK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hamburg Helmut Schmidt Airport', 'DE', 'HAM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Noi Bai International Airport', 'VN', 'HAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jos√© Mart√≠ International Airport', 'CU', 'HAV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Helsinki Vantaa Airport', 'FI', 'HEL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Heraklion International Nikos Kazantzakis Airport', 'GR', 'HER');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Baita International Airport', 'CN', 'HET');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Egal International Airport', 'SO', 'HGA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hangzhou Xiaoshan International Airport', 'CN', 'HGH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Range Regional Airport', 'US', 'HIB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lake Havasu City International Airport', 'US', 'HII');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Honiara International Airport', 'SB', 'HIR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hong Kong International Airport', 'HK', 'HKG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Phuket International Airport', 'TH', 'HKT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Holloman Air Force Base', 'US', 'HMN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Ignacio P. Garcia International Airport', 'MX', 'HMO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tokyo Haneda International Airport', 'JP', 'HND');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Daniel K Inouye International Airport', 'US', 'HNL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('William P Hobby Airport', 'US', 'HOU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Taiping Airport', 'CN', 'HRB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Robert Gabriel Mugabe International Airport', 'ZW', 'HRE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hurghada International Airport', 'EG', 'HRG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mattala Rajapaksa International Airport', 'LK', 'HRI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kharkiv International Airport', 'UA', 'HRK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hazrat Sultan International Airport', 'KZ', 'HSA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Huntsville International Carl T Jones Field', 'US', 'HSV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tri-State/Milton J. Ferguson Field', 'US', 'HTS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rajiv Gandhi International Airport', 'IN', 'HYD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Washington Dulles International Airport', 'US', 'IAD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('George Bush Intercontinental Houston Airport', 'US', 'IAH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Incheon International Airport', 'KR', 'ICN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Wichita Eisenhower National Airport', 'US', 'ICT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Imam Khomeini International Airport', 'IR', 'IKA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Indianapolis International Airport', 'US', 'IND');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Islamabad International Airport', 'PK', 'ISB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('S√ºleyman Demirel International Airport', 'TR', 'ISE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('ƒ∞stanbul Atat√ºrk Airport', 'TR', 'ISL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('ƒ∞stanbul Airport', 'TR', 'IST');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Osaka International Airport', 'JP', 'ITM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jackson-Medgar Wiley Evers International Airport', 'US', 'JAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jacksonville International Airport', 'US', 'JAX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Abdulaziz International Airport', 'SA', 'JED');
INSERT INTO airports (name, country_code, iata_code) VALUES ('John F Kennedy International Airport', 'US', 'JFK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Joplin Regional Airport', 'US', 'JLN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('OR Tambo International Airport', 'ZA', 'JNB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Juba International Airport', 'SS', 'JUB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mallam Aminu International Airport', 'NG', 'KAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Boryspil International Airport', 'UA', 'KBP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Keflavik International Airport', 'IS', 'KEF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sary-Arka Airport', 'KZ', 'KGF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kigali International Airport', 'RW', 'KGL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kaohsiung International Airport', 'TW', 'KHH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Khabarovsk-Novy Airport', 'RU', 'KHV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Norman Manley International Airport', 'JM', 'KIN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kansai International Airport', 'JP', 'KIX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Krasnoyarsk International Airport', 'RU', 'KJA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kunming Changshui International Airport', 'CN', 'KMG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kinmen Airport', 'TW', 'KNH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kualanamu International Airport', 'ID', 'KNO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kagoshima Airport', 'JP', 'KOJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Krak√≥w John Paul II International Airport', 'PL', 'KRK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Khartoum International Airport', 'SD', 'KRT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tribhuvan International Airport', 'NP', 'KTM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Katowice International Airport', 'PL', 'KTW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kurumoch International Airport', 'RU', 'KUF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kuala Lumpur International Airport', 'MY', 'KUL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kunsan Air Base', 'KR', 'KUV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Longdongbao Airport', 'CN', 'KWE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kuwait International Airport', 'KW', 'KWI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Guilin Liangjiang International Airport', 'CN', 'KWL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kazan International Airport', 'RU', 'KZN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Quatro de Fevereiro Airport', 'AO', 'LAD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('McCarran International Airport', 'US', 'LAS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Los Angeles International Airport', 'US', 'LAX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Leeds Bradford Airport', 'GB', 'LBA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lubbock Preston Smith International Airport', 'US', 'LBB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Larnaca International Airport', 'CY', 'LCA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rickenbacker International Airport', 'US', 'LCK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pulkovo Airport', 'RU', 'LED');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Leipzig/Halle Airport', 'DE', 'LEJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Blue Grass Airport', 'US', 'LEX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Langley Air Force Base', 'US', 'LFI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lafayette Regional Airport', 'US', 'LFT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('La Guardia Airport', 'US', 'LGA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Li√®ge Airport', 'BE', 'LGG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('London Gatwick Airport', 'GB', 'LGW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('London Heathrow Airport', 'GB', 'LHR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lake Havasu City International Airport', 'US', 'LHS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jorge Ch√°vez International Airport', 'PE', 'LIM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Milano Linate Airport', 'IT', 'LIN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Daniel Oduber Quiros International Airport', 'CR', 'LIR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Humberto Delgado Airport (Lisbon Portela Airport)', 'PT', 'LIS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bill & Hillary Clinton National Airport/Adams Field', 'US', 'LIT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ljubljana Jo≈æe Puƒçnik Airport', 'SI', 'LJU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('RAF Lakenheath', 'GB', 'LKZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lule√• Airport', 'SE', 'LLA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cagayan North International Airport', 'PH', 'LLC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Valle del Fuerte International Airport', 'MX', 'LMM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Murtala Muhammed International Airport', 'NG', 'LOS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gran Canaria Airport', 'ES', 'LPA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Liverpool John Lennon Airport', 'GB', 'LPL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bassel Al-Assad International Airport', 'SY', 'LTK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('London Luton Airport', 'GB', 'LTN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Altus Air Force Base', 'US', 'LTS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cotopaxi International Airport', 'EC', 'LTX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Luke Air Force Base', 'US', 'LUF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kenneth Kaunda International Airport', 'ZM', 'LUN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Luxembourg-Findel International Airport', 'LU', 'LUX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lyon Saint-Exup√©ry Airport', 'FR', 'LYS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chennai International Airport', 'IN', 'MAA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Adolfo Su√°rez Madrid‚ÄìBarajas Airport', 'ES', 'MAD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Manchester Airport', 'GB', 'MAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Eduardo Gomes International Airport', 'BR', 'MAO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Moi International Airport', 'KE', 'MBA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('MBS International Airport', 'US', 'MBS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mac Dill Air Force Base', 'US', 'MCF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kansas City International Airport', 'US', 'MCI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Orlando International Airport', 'US', 'MCO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Muscat International Airport', 'OM', 'MCT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mandalay International Airport', 'MM', 'MDL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chicago Midway International Airport', 'US', 'MDW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Prince Mohammad Bin Abdulaziz Airport', 'SA', 'MED');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Melbourne International Airport', 'AU', 'MEL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Memphis International Airport', 'US', 'MEM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Licenciado Benito Juarez International Airport', 'MX', 'MEX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mesquite International Airport', 'US', 'MFH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Macau International Airport', 'MO', 'MFM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dobbins Air Reserve Base', 'US', 'MGE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Montgomery Regional (Dannelly Field) Airport', 'US', 'MGM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mashhad International Airport', 'IR', 'MHD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Manchester-Boston Regional Airport', 'US', 'MHT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('RAF Mildenhall', 'GB', 'MHZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Miami International Airport', 'US', 'MIA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Mitchell International Airport', 'US', 'MKE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Malta International Airport', 'MT', 'MLA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mal√© International Airport', 'MV', 'MLE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Quad City International Airport', 'US', 'MLI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Monroe Regional Airport', 'US', 'MLU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Malm√∂ Sturup Airport', 'SE', 'MMX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mussanah Airport', 'OM', 'MNH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ninoy Aquino International Airport', 'PH', 'MNL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mobile Regional Airport', 'US', 'MOB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Maputo Airport', 'MZ', 'MPM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Marseille Provence Airport', 'FR', 'MRS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sir Seewoosagur Ramgoolam International Airport', 'MU', 'MRU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Dane County Regional Truax Field', 'US', 'MSN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Minneapolis‚ÄìSaint Paul International Airport / Wold‚ÄìChamberlain Field', 'US', 'MSP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Minsk National Airport', 'BY', 'MSQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Louis Armstrong New Orleans International Airport', 'US', 'MSY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Mariano Escobedo International Airport', 'MX', 'MTY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Munich Airport', 'DE', 'MUC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mountain Home Air Force Base', 'US', 'MUO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Carrasco International /General C L Berisso Airport', 'UY', 'MVD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Muan International Airport', 'KR', 'MWX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Malpensa International Airport', 'IT', 'MXP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Rafael Buelna International Airport', 'MX', 'MZT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Naples International Airport', 'IT', 'NAP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lynden Pindling International Airport', 'BS', 'NAS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('S√£o Gon√ßalo do Amarante - Governador Alu√≠zio Alves International Airport', 'BR', 'NAT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Beijing Nanyuan Airport', 'CN', 'NAY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Enfidha - Hammamet International Airport', 'TN', 'NBE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jomo Kenyatta International Airport', 'KE', 'NBO');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Nice-C√¥te d\'Azur Airport', 'FR', 'NCE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Newcastle Airport', 'GB', 'NCL');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'N\'Djamena International Airport', 'TD', 'NDJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ningbo Lishe International Airport', 'CN', 'NGB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chubu Centrair International Airport', 'JP', 'NGO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Diori Hamani International Airport', 'NE', 'NIM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nouakchott‚ÄìOumtounsy International Airport', 'MR', 'NKC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nanjing Lukou Airport', 'CN', 'NKG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Santa Luc√≠a Air Force Base / Felipe Angeles International Airport', 'MX', 'NLU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nanning Wuxu Airport', 'CN', 'NNG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nephi-Central Utah International Airport', 'US', 'NPH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nursultan Nazarbayev International Airport', 'KZ', 'NQZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Narita International Airport', 'JP', 'NRT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nuremberg Airport', 'DE', 'NUE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Norwich International Airport', 'GB', 'NWI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Metropolitan Oakland International Airport', 'US', 'OAK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Odessa International Airport', 'UA', 'ODS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Naha Airport / JASDF Naha Air Base', 'JP', 'OKA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Will Rogers World Airport', 'US', 'OKC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yokota Air Base', 'JP', 'OKO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Eppley Airfield', 'US', 'OMA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ontario International Airport', 'US', 'ONT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Francisco de S√° Carneiro Airport', 'PT', 'OPO');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Chicago O\'Hare International Airport', 'US', 'ORD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Norfolk International Airport', 'US', 'ORF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Cork Airport', 'IE', 'ORK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Paris-Orly Airport', 'FR', 'ORY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Oslo Gardermoen Airport', 'NO', 'OSL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Osan Air Base', 'KR', 'OSN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Henri CoandƒÉ International Airport', 'RO', 'OTP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ouagadougou Airport', 'BF', 'OUA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tolmachevo Airport', 'RU', 'OVB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tyndall Air Force Base', 'US', 'PAM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Palm Beach International Airport', 'US', 'PBI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Jo√£o Paulo II Airport', 'PT', 'PDL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Portland International Airport', 'US', 'PDX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Beijing Capital International Airport', 'CN', 'PEK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Perth International Airport', 'AU', 'PER');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Paphos International Airport', 'CY', 'PFO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Newport News Williamsburg International Airport', 'US', 'PHF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Philadelphia International Airport', 'US', 'PHL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Phoenix Sky Harbor International Airport', 'US', 'PHX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Wayne A. Downing Peoria International Airport', 'US', 'PIA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pittsburgh International Airport', 'US', 'PIT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Beijing Daxing International Airport', 'CN', 'PKX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Palma De Mallorca Airport', 'ES', 'PMI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Falcone‚ÄìBorsellino Airport', 'IT', 'PMO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Phnom Penh International Airport', 'KH', 'PNH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Port Moresby Jacksons International Airport', 'PG', 'POM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pozna≈Ñ-≈Åawica Airport', 'PL', 'POZ');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Faa\'a International Airport', 'PF', 'PPT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Prescott International Airport - Ernest A. Love Field', 'US', 'PRC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('V√°clav Havel Airport Prague', 'CZ', 'PRG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pri≈°tina Adem Jashari International Airport', 'XK', 'PRN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pisa International Airport', 'IT', 'PSA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Pointe-√†-Pitre Le Raizet', 'GP', 'PTP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tocumen International Airport', 'PA', 'PTY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Punta Cana International Airport', 'DO', 'PUJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Gimhae International Airport', 'KR', 'PUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Theodore Francis Green State Airport', 'US', 'PVD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shanghai Pudong International Airport', 'CN', 'PVG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Licenciado Gustavo D√≠az Ordaz International Airport', 'MX', 'PVR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Provo-Utah Lake International Airport', 'US', 'PVU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Portland International Jetport', 'US', 'PWM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Akwa Ibom International Airport', 'NG', 'QUO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rarotonga International Airport', 'CK', 'RAR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Raleigh Durham International Airport', 'US', 'RDU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Siem Reap International Airport', 'KH', 'REP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Chicago Rockford International Airport', 'US', 'RFD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yangon International Airport', 'MM', 'RGN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Richmond International Airport', 'US', 'RIC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Riga International Airport', 'LV', 'RIX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ramstein Air Base', 'DE', 'RMS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Randolph Air Force Base', 'US', 'RND');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Reno Tahoe International Airport', 'US', 'RNO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Roanoke‚ÄìBlacksburg Regional Airport', 'US', 'ROA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Roberts International Airport', 'LR', 'ROB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Greater Rochester International Airport', 'US', 'ROC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Platov International Airport', 'RU', 'ROV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Rochester International Airport', 'US', 'RST');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Southwest Florida International Airport', 'US', 'RSW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Khaled International Airport', 'SA', 'RUH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Monse√±or √ìscar Arnulfo Romero International Airport', 'SV', 'SAL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('San Diego International Airport', 'US', 'SAN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('San Antonio International Airport', 'US', 'SAT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Savannah Hilton Head International Airport', 'US', 'SAV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Istanbul Sabiha G√∂k√ßen International Airport', 'TR', 'SAW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('San Bernardino International Airport', 'US', 'SBD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('South Bend Regional Airport', 'US', 'SBN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Comodoro Arturo Merino Ben√≠tez International Airport', 'CL', 'SCL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Santiago de Compostela Airport', 'ES', 'SCQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Louisville Muhammad Ali International Airport', 'US', 'SDF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sendai Airport', 'JP', 'SDJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Las Am√©ricas International Airport', 'DO', 'SDQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Seattle Tacoma International Airport', 'US', 'SEA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Seychelles International Airport', 'SC', 'SEZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Orlando Sanford International Airport', 'US', 'SFB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('San Francisco International Airport', 'US', 'SFO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Springfield Branson National Airport', 'US', 'SGF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tan Son Nhat International Airport', 'VN', 'SGN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Saint George-Southwest Utah International Airport', 'US', 'SGU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shanghai Hongqiao International Airport', 'CN', 'SHA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shenyang Taoxian International Airport', 'CN', 'SHE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sharjah International Airport', 'AE', 'SHJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('King Mswati III International Airport', 'SZ', 'SHO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Am√≠lcar Cabral International Airport', 'CV', 'SID');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Singapore Changi Airport', 'SG', 'SIN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Simferopol International Airport', 'UA', 'SIP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Norman Y. Mineta San Jose International Airport', 'US', 'SJC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Los Cabos International Airport', 'MX', 'SJD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sarajevo International Airport', 'BA', 'SJJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Luis Munoz Marin International Airport', 'PR', 'SJU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Fairchild Air Force Base', 'US', 'SKA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Thessaloniki Macedonia International Airport', 'GR', 'SKG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Skopje International Airport', 'MK', 'SKP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sialkot International Airport', 'PK', 'SKT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Salt Lake City International Airport', 'US', 'SLC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sacramento International Airport', 'US', 'SMF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('John Wayne Airport-Orange County Airport', 'US', 'SNA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shannon Airport', 'IE', 'SNN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sofia Airport', 'BG', 'SOF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Domine Eduard Osok Airport', 'ID', 'SOQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Southampton Airport', 'GB', 'SOU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('La Palma Airport', 'ES', 'SPC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Abraham Lincoln Capital Airport', 'US', 'SPI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sheppard Air Force Base-Wichita Falls Municipal Airport', 'US', 'SPS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sarasota Bradenton International Airport', 'US', 'SRQ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Deputado Luiz Eduardo Magalh√£es International Airport', 'BR', 'SSA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shaw Air Force Base', 'US', 'SSC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('St Louis Lambert International Airport', 'US', 'STL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('London Stansted Airport', 'GB', 'STN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Stuttgart Airport', 'DE', 'STR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Juanda International Airport', 'ID', 'SUB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Spirit of St Louis Airport', 'US', 'SUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Travis Air Force Base', 'US', 'SUU');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sioux Gateway Airport / Brigadier General Bud Day Field', 'US', 'SUX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Stavanger Airport Sola', 'NO', 'SVG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sheremetyevo International Airport', 'RU', 'SVO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Koltsovo Airport', 'RU', 'SVX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Princess Juliana International Airport', 'SX', 'SXM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sydney Kingsford Smith International Airport', 'AU', 'SYD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Syracuse Hancock International Airport', 'US', 'SYR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Sanya Phoenix International Airport', 'CN', 'SYX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Shiraz Shahid Dastghaib International Airport', 'IR', 'SYZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Whiteman Air Force Base', 'US', 'SZL');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Shenzhen Bao\'an International Airport', 'CN', 'SZX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Szczecin-Goleni√≥w "Solidarno≈õƒá" Airport', 'PL', 'SZZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tashkent International Airport', 'UZ', 'TAS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tbilisi International Airport', 'GE', 'TBS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tabriz International Airport', 'IR', 'TBZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('McChord Air Force Base', 'US', 'TCM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lajes Airport', 'PT', 'TER');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tenerife Norte Airport', 'ES', 'TFN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tenerife South Airport', 'ES', 'TFS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Podgorica Airport / Podgorica Golubovci Airbase', 'ME', 'TGD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mehrabad International Airport', 'IR', 'THR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tirana International Airport Mother Teresa', 'AL', 'TIA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('General Abelardo L. Rodr√≠guez International Airport', 'MX', 'TIJ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tinker Air Force Base', 'US', 'TIK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tripoli International Airport', 'LY', 'TIP');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tallahassee Regional Airport', 'US', 'TLH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lennart Meri Tallinn Airport', 'EE', 'TLL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Toulouse-Blagnac Airport', 'FR', 'TLS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ben Gurion International Airport', 'IL', 'TLV');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yaoqiang Airport', 'CN', 'TNA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ivato Airport', 'MG', 'TNR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Toledo Express Airport', 'US', 'TOL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Troms√∏ Airport', 'NO', 'TOS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tampa International Airport', 'US', 'TPA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Taiwan Taoyuan International Airport', 'TW', 'TPE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Trondheim Airport V√¶rnes', 'NO', 'TRD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tri-Cities Regional TN/VA Airport', 'US', 'TRI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Turin Airport', 'IT', 'TRN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Trivandrum International Airport', 'IN', 'TRV');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Treviso-Sant\'Angelo Airport', 'IT', 'TSF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tianjin Binhai International Airport', 'CN', 'TSN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tulsa International Airport', 'US', 'TUL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tunis Carthage International Airport', 'TN', 'TUN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Tucson International Airport / Morris Air National Guard Base', 'US', 'TUS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Taiyuan Wusu Airport', 'CN', 'TYN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('McGhee Tyson Airport', 'US', 'TYS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Trabzon International Airport', 'TR', 'TZX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ulaanbaatar Chinggis Khaan International Airport', 'MN', 'UBN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ufa International Airport', 'RU', 'UFA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Mariscal Sucre International Airport', 'EC', 'UIO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Buyant-Ukhaa International Airport', 'MN', 'ULN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hasanuddin International Airport', 'ID', 'UPG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('√úr√ºmqi Diwopu International Airport', 'CN', 'URC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('South Valley International Airport', 'US', 'UTH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lilbuanaka International Airport/Heliport/Airforcebase/TestingSite/Flightschool', 'DZ', 'UUK');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Varna Airport', 'BG', 'VAR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vandenberg Air Force Base', 'US', 'VBG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Venice Marco Polo Airport', 'IT', 'VCE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('North Las Vegas Metropolitan International Airport', 'US', 'VGT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vienna International Airport', 'AT', 'VIE');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Visalia International Airport', 'US', 'VIS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vnukovo International Airport', 'RU', 'VKO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Bauerfield International Airport', 'VU', 'VLI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vilnius International Airport', 'LT', 'VNO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Destin-Fort Walton Beach Airport', 'US', 'VPS');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Juan Gualberto Gomez International Airport', 'CU', 'VRA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Verona Villafranca Airport', 'IT', 'VRN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Viru Viru International Airport', 'BO', 'VVI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vladivostok International Airport', 'RU', 'VVO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Warsaw Chopin Airport', 'PL', 'WAW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Hosea Kutako International Airport', 'NA', 'WDH');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Wellington International Airport', 'NZ', 'WLG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Modlin Airport', 'PL', 'WMI');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Wenzhou Longwan International Airport', 'CN', 'WNZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Robins Air Force Base', 'US', 'WRB');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Copernicus Wroc≈Çaw Airport', 'PL', 'WRO');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Wuhan Tianhe International Airport', 'CN', 'WUH');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'Xi\'an Xianyang International Airport', 'CN', 'XIY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Xiamen Gaoqi International Airport', 'CN', 'XMN');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Nanaimo International Air And Space Port / RCAF Nanaimo Base', 'CA', 'YCD');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Edmonton International Airport', 'CA', 'YEG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Halifax / Stanfield International Airport', 'CA', 'YHZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Kelowna International Airport', 'CA', 'YLW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yantai Penglai International Airport', 'CN', 'YNT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Ottawa Macdonald-Cartier International Airport', 'CA', 'YOW');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Montreal / Pierre Elliott Trudeau International Airport', 'CA', 'YUL');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yuma International Airport / Marine Corps Air Station Yuma', 'US', 'YUM');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Vancouver International Airport', 'CA', 'YVR');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Winnipeg / James Armstrong Richardson International Airport', 'CA', 'YWG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Abbotsford International Airport', 'CA', 'YXX');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Whitehorse / Erik Nielsen International Airport', 'CA', 'YXY');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Calgary International Airport', 'CA', 'YYC');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Victoria International Airport', 'CA', 'YYJ');
INSERT INTO airports (name, country_code, iata_code) VALUES (E'St. John\'s International Airport', 'CA', 'YYT');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Lester B. Pearson International Airport', 'CA', 'YYZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Yellowknife International Airport', 'CA', 'YZF');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Zagreb Airport', 'HR', 'ZAG');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Zhukovsky International Airport', 'RU', 'ZIA');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Abeid Amani Karume International Airport', 'TZ', 'ZNZ');
INSERT INTO airports (name, country_code, iata_code) VALUES ('Z√ºrich Airport', 'CH', 'ZRH');
