UPDATE countries SET dhis2_code = 'hGJnSu14S4H' WHERE name = E'Afghanistan';
UPDATE countries SET dhis2_code = 'jNHN0pOchoB' WHERE name = E'Aland Islands';
UPDATE countries SET dhis2_code = 'Bh4wWzctSjb' WHERE name = E'Albania';
UPDATE countries SET dhis2_code = 'fjla1buVNJ1' WHERE name = E'Algeria';
UPDATE countries SET dhis2_code = 'hYLZM1WibDG' WHERE name = E'American Samoa';
UPDATE countries SET dhis2_code = 'Vy2kZ2xdywD' WHERE name = E'Andorra';
UPDATE countries SET dhis2_code = 'SMRVOAezK6m' WHERE name = E'Angola';
UPDATE countries SET dhis2_code = 'TAtDifm7RQ2' WHERE name = E'Anguilla';
UPDATE countries SET dhis2_code = 'PJlpC0ulmxS' WHERE name = E'Antarctica';
UPDATE countries SET dhis2_code = 'zbLeaXBzQ0r' WHERE name = E'Antigua and Barbuda';
UPDATE countries SET dhis2_code = 'ywRcbgzfJPh' WHERE name = E'Argentina';
UPDATE countries SET dhis2_code = 'LOaaG2lAIFa' WHERE name = E'Armenia';
UPDATE countries SET dhis2_code = 't54DjoTR2p6' WHERE name = E'Aruba';
UPDATE countries SET dhis2_code = 'yW6IdVQov4u' WHERE name = E'Australia';
UPDATE countries SET dhis2_code = 'm5ziJSjzRPE' WHERE name = E'Austria';
UPDATE countries SET dhis2_code = 'ea6F8vmxRXr' WHERE name = E'Azerbaijan';
UPDATE countries SET dhis2_code = 'kzAod6laMdd' WHERE name = E'Bahamas';
UPDATE countries SET dhis2_code = 'iJ2Z9ipAEe6' WHERE name = E'Bahrain';
UPDATE countries SET dhis2_code = 'Tk7FMD1MasS' WHERE name = E'Bangladesh';
UPDATE countries SET dhis2_code = 'ynsA4tpFPiu' WHERE name = E'Barbados';
UPDATE countries SET dhis2_code = 'agD66qYjXBj' WHERE name = E'Belarus';
UPDATE countries SET dhis2_code = 'cPIpkDRqE0s' WHERE name = E'Belgium';
UPDATE countries SET dhis2_code = 'ihkgYyvIpoJ' WHERE name = E'Belize';
UPDATE countries SET dhis2_code = 'tbGOoDQGapm' WHERE name = E'Benin';
UPDATE countries SET dhis2_code = 'ofZoh1cmVIS' WHERE name = E'Bermuda';
UPDATE countries SET dhis2_code = 'TqHJcgfYYO7' WHERE name = E'Bhutan';
UPDATE countries SET dhis2_code = 'cFC9TG5T6rk' WHERE name = E'Bolivia (Plurinational State of)';
UPDATE countries SET dhis2_code = 'JEvbk1d5kZz' WHERE name = E'Bonaire, Sint Eustatius and Saba';
UPDATE countries SET dhis2_code = 'W0yLTk0cm95' WHERE name = E'Bosnia and Herzegovina';
UPDATE countries SET dhis2_code = 'HwxSk7Bydgv' WHERE name = E'Botswana';
UPDATE countries SET dhis2_code = 'QUDg3f2Vykg' WHERE name = E'Bouvet Island';
UPDATE countries SET dhis2_code = 'k7rCWMSHHnW' WHERE name = E'Brazil';
UPDATE countries SET dhis2_code = 'XPbtS9mdWu0' WHERE name = E'British Indian Ocean Territory';
UPDATE countries SET dhis2_code = 'RhgmAKhAC5q' WHERE name = E'Brunei Darussalam';
UPDATE countries SET dhis2_code = 'OxCmeYyS27P' WHERE name = E'Bulgaria';
UPDATE countries SET dhis2_code = 'ysELYlzPrdm' WHERE name = E'Burkina Faso';
UPDATE countries SET dhis2_code = 'Tip7kcFjydR' WHERE name = E'Burundi';
UPDATE countries SET dhis2_code = 'UNQndlLuT6z' WHERE name = E'Cabo Verde';
UPDATE countries SET dhis2_code = 'ZMRxkXvOSHd' WHERE name = E'Cambodia';
UPDATE countries SET dhis2_code = 'hYinhh33Smb' WHERE name = E'Cameroon';
UPDATE countries SET dhis2_code = 'e73WCSot5Kz' WHERE name = E'Canada';
UPDATE countries SET dhis2_code = 'jg2D4zXeOEW' WHERE name = E'Cayman Islands';
UPDATE countries SET dhis2_code = 'oEo4sOKVbxo' WHERE name = E'Central African Republic';
UPDATE countries SET dhis2_code = 'RIN4O3DOJ7i' WHERE name = E'Chad';
UPDATE countries SET dhis2_code = 'iyOIO7u3rp2' WHERE name = E'Chile';
UPDATE countries SET dhis2_code = 'IoNVJbgYCgK' WHERE name = E'China';
UPDATE countries SET dhis2_code = 'cns3VhQOOLT' WHERE name = E'Christmas Island';
UPDATE countries SET dhis2_code = 'djBN4hznuVx' WHERE name = E'Cocos (Keeling) Islands';
UPDATE countries SET dhis2_code = 'Ap6L7fXfDeR' WHERE name = E'Colombia';
UPDATE countries SET dhis2_code = 'ekNvWlcIqc6' WHERE name = E'Comoros';
UPDATE countries SET dhis2_code = 'gdaMM4iITdU' WHERE name = E'Congo';
UPDATE countries SET dhis2_code = 'TULAmCgYERZ' WHERE name = E'Congo (Democratic Republic of the)';
UPDATE countries SET dhis2_code = 'df2Z1m4wiDH' WHERE name = E'Cook Islands';
UPDATE countries SET dhis2_code = 'gUv8NQnweWA' WHERE name = E'Costa Rica';
UPDATE countries SET dhis2_code = 'irKCzydHfvQ' WHERE name = E'Cote d\'Ivoire';
UPDATE countries SET dhis2_code = 'z90AdvvHWFs' WHERE name = E'Croatia';
UPDATE countries SET dhis2_code = 'slZk3s6xPoM' WHERE name = E'Cuba';
UPDATE countries SET dhis2_code = 'hH0Hy1NEJLt' WHERE name = E'Curacao';
UPDATE countries SET dhis2_code = 'LdQF1sPxdxF' WHERE name = E'Cyprus';
UPDATE countries SET dhis2_code = 'EbLJJJfvsfk' WHERE name = E'Czech Republic';
UPDATE countries SET dhis2_code = 'Dbq4nnM2YAX' WHERE name = E'Denmark';
UPDATE countries SET dhis2_code = 'j18ViLv3bH0' WHERE name = E'Djibouti';
UPDATE countries SET dhis2_code = 'on9E0VYO7Fn' WHERE name = E'Dominica';
UPDATE countries SET dhis2_code = 'VEzuYX8hkAt' WHERE name = E'Dominican Republic';
UPDATE countries SET dhis2_code = 'WAdbLIjOMui' WHERE name = E'Ecuador';
UPDATE countries SET dhis2_code = 'HStdRZPlcpd' WHERE name = E'Egypt';
UPDATE countries SET dhis2_code = 'LqtYpN1esYr' WHERE name = E'El Salvador';
UPDATE countries SET dhis2_code = 'D7X0HISqZFG' WHERE name = E'Equatorial Guinea';
UPDATE countries SET dhis2_code = 'bC7LkeM89FC' WHERE name = E'Eritrea';
UPDATE countries SET dhis2_code = 'qEznaEpFnJr' WHERE name = E'Estonia';
UPDATE countries SET dhis2_code = 'ZNlpMAULihV' WHERE name = E'Ethiopia';
UPDATE countries SET dhis2_code = 'bef2vVeR23P' WHERE name = E'Falkland Islands (Malvinas)';
UPDATE countries SET dhis2_code = 't3xIkfi2H9B' WHERE name = E'Faroe Islands';
UPDATE countries SET dhis2_code = 'zFR8DxViVCF' WHERE name = E'Fiji';
UPDATE countries SET dhis2_code = 'CVzjZYuAWYN' WHERE name = E'Finland';
UPDATE countries SET dhis2_code = 'yUGs4f8ERRO' WHERE name = E'France';
UPDATE countries SET dhis2_code = 'buoSIj3Vwra' WHERE name = E'French Guiana';
UPDATE countries SET dhis2_code = 'tp6tO0mcWi3' WHERE name = E'French Polynesia';
UPDATE countries SET dhis2_code = 'kCQuehGwFao' WHERE name = E'French Southern Territories';
UPDATE countries SET dhis2_code = 'ITLH48ZUffA' WHERE name = E'Gabon';
UPDATE countries SET dhis2_code = 'ACPpkQT2y2F' WHERE name = E'Gambia';
UPDATE countries SET dhis2_code = 'QZe0b0vBdRx' WHERE name = E'Georgia';
UPDATE countries SET dhis2_code = 'F7VjKLOSKYQ' WHERE name = E'Germany';
UPDATE countries SET dhis2_code = 'O80pXVxnTv0' WHERE name = E'Ghana';
UPDATE countries SET dhis2_code = 'XgXpDOKZfIX' WHERE name = E'Gibraltar';
UPDATE countries SET dhis2_code = 'ic83mV0Np1K' WHERE name = E'Greece';
UPDATE countries SET dhis2_code = 'PxDnUHCZFYV' WHERE name = E'Greenland';
UPDATE countries SET dhis2_code = 'F0bPny0RATH' WHERE name = E'Grenada';
UPDATE countries SET dhis2_code = 'zYa1MKY2G3d' WHERE name = E'Guadeloupe';
UPDATE countries SET dhis2_code = 'lbhBF8S5JoR' WHERE name = E'Guam';
UPDATE countries SET dhis2_code = 'okjtUpqkBY0' WHERE name = E'Guatemala';
UPDATE countries SET dhis2_code = 'QlGDgVLB9Mg' WHERE name = E'Guernsey';
UPDATE countries SET dhis2_code = 'yqF1sleXWu4' WHERE name = E'Guinea';
UPDATE countries SET dhis2_code = 'b226WlAQhQT' WHERE name = E'Guinea-Bissau';
UPDATE countries SET dhis2_code = 'l2pI0kEQo1x' WHERE name = E'Guyana';
UPDATE countries SET dhis2_code = 'hgQ5KIZRzrq' WHERE name = E'Haiti';
UPDATE countries SET dhis2_code = 'UqDKVzW7N6x' WHERE name = E'Heard Island and McDonald Islands';
UPDATE countries SET dhis2_code = 'UPgq5yBhzma' WHERE name = E'Holy See';
UPDATE countries SET dhis2_code = 'guqDJE0tEhz' WHERE name = E'Honduras';
UPDATE countries SET dhis2_code = 'ehSp3aJDOhB' WHERE name = E'Hong Kong';
UPDATE countries SET dhis2_code = 'M0vvlGGO2ET' WHERE name = E'Hungary';
UPDATE countries SET dhis2_code = 'oCqAUWB1AK0' WHERE name = E'Iceland';
UPDATE countries SET dhis2_code = 'snaU0ZUJ03A' WHERE name = E'India';
UPDATE countries SET dhis2_code = 'Ls7DhgvN3M9' WHERE name = E'Indonesia';
UPDATE countries SET dhis2_code = 'bvxdOvWV0Qt' WHERE name = E'Iran (Islamic Republic of)';
UPDATE countries SET dhis2_code = 'kpEvOGtOaJa' WHERE name = E'Iraq';
UPDATE countries SET dhis2_code = 'PahOgLwCZMg' WHERE name = E'Ireland';
UPDATE countries SET dhis2_code = 'GgpJFlPRlXZ' WHERE name = E'Isle of Man';
UPDATE countries SET dhis2_code = 'GeUERumufaz' WHERE name = E'Israel';
UPDATE countries SET dhis2_code = 'sHSgXweCFwT' WHERE name = E'Italy';
UPDATE countries SET dhis2_code = 'c2gkADoIq0a' WHERE name = E'Jamaica';
UPDATE countries SET dhis2_code = 'Iyxt9soGc5i' WHERE name = E'Japan';
UPDATE countries SET dhis2_code = 'wW0cTJr4QvY' WHERE name = E'Jersey';
UPDATE countries SET dhis2_code = 'Dz0ikE8Opef' WHERE name = E'Jordan';
UPDATE countries SET dhis2_code = 'CxA2f0AZM2H' WHERE name = E'Kazakhstan';
UPDATE countries SET dhis2_code = 'cCIXvPLzsUj' WHERE name = E'Kenya';
UPDATE countries SET dhis2_code = 'ysv73lzyfPU' WHERE name = E'Kiribati';
UPDATE countries SET dhis2_code = 'W26NWlPaIJD' WHERE name = E'Korea (Democratic People\'s Republic of)';
UPDATE countries SET dhis2_code = 'wrMAg1FeNEH' WHERE name = E'Korea (Republic of)';
UPDATE countries SET dhis2_code = 'Rk3W9BRd1D6' WHERE name = E'Kuwait';
UPDATE countries SET dhis2_code = 'FLWvmb7Fngv' WHERE name = E'Kyrgyzstan';
UPDATE countries SET dhis2_code = 'hmmPhRwpYlN' WHERE name = E'Lao People\'s Democratic Republic';
UPDATE countries SET dhis2_code = 'PNloUnfVthd' WHERE name = E'Latvia';
UPDATE countries SET dhis2_code = 'khbm7vs5OVf' WHERE name = E'Lebanon';
UPDATE countries SET dhis2_code = 'JBUNAoY2UCR' WHERE name = E'Lesotho';
UPDATE countries SET dhis2_code = 'jX4Q0C4e5Wz' WHERE name = E'Liberia';
UPDATE countries SET dhis2_code = 'aWdKmnUbyq8' WHERE name = E'Libya';
UPDATE countries SET dhis2_code = 'YFBUwHreFty' WHERE name = E'Liechtenstein';
UPDATE countries SET dhis2_code = 'NgE7dxvafzN' WHERE name = E'Lithuania';
UPDATE countries SET dhis2_code = 'Lcpj9JRPN6A' WHERE name = E'Luxembourg';
UPDATE countries SET dhis2_code = 'Ud37kwuqYOX' WHERE name = E'Macao';
UPDATE countries SET dhis2_code = 'ol616QD7y9v' WHERE name = E'Macedonia (the former Yugoslav Republic of)';
UPDATE countries SET dhis2_code = 'V9dlKIBeEt5' WHERE name = E'Madagascar';
UPDATE countries SET dhis2_code = 'ZJKBOoWeZK8' WHERE name = E'Malawi';
UPDATE countries SET dhis2_code = 'TbqJLwX75MB' WHERE name = E'Malaysia';
UPDATE countries SET dhis2_code = 'cz1jjVYazCU' WHERE name = E'Maldives';
UPDATE countries SET dhis2_code = 'vaAP0kIZoWc' WHERE name = E'Mali';
UPDATE countries SET dhis2_code = 'oUZwMtRc9UZ' WHERE name = E'Malta';
UPDATE countries SET dhis2_code = 'FTShlPn5hKZ' WHERE name = E'Marshall Islands';
UPDATE countries SET dhis2_code = 'PXW5S4tsyeU' WHERE name = E'Martinique';
UPDATE countries SET dhis2_code = 'zSqkhuvMIJx' WHERE name = E'Mauritania';
UPDATE countries SET dhis2_code = 'phk8e9YUIyk' WHERE name = E'Mauritius';
UPDATE countries SET dhis2_code = 'Lr41AxFkOoQ' WHERE name = E'Mayotte';
UPDATE countries SET dhis2_code = 'AZKUCGpgtzT' WHERE name = E'Mexico';
UPDATE countries SET dhis2_code = 'gr2CYy3Dr56' WHERE name = E'Micronesia (Federated States of)';
UPDATE countries SET dhis2_code = 'n8HXfqEC7qW' WHERE name = E'Moldova (Republic of)';
UPDATE countries SET dhis2_code = 'zJVqezCOVEw' WHERE name = E'Monaco';
UPDATE countries SET dhis2_code = 'goMYgrWwzxj' WHERE name = E'Mongolia';
UPDATE countries SET dhis2_code = 'YMAWw8lGmVz' WHERE name = E'Montenegro';
UPDATE countries SET dhis2_code = 'BFKxH53DgZ4' WHERE name = E'Montserrat';
UPDATE countries SET dhis2_code = 'jpFFUofjPzL' WHERE name = E'Morocco';
UPDATE countries SET dhis2_code = 'Qodq6bOTBgk' WHERE name = E'Mozambique';
UPDATE countries SET dhis2_code = 'HHpmrOG4Oah' WHERE name = E'Myanmar';
UPDATE countries SET dhis2_code = 'o3FDUKEuK9I' WHERE name = E'Namibia';
UPDATE countries SET dhis2_code = 'CqUzE4oAeMo' WHERE name = E'Nauru';
UPDATE countries SET dhis2_code = 'G3wJAW7bEqO' WHERE name = E'Nepal';
UPDATE countries SET dhis2_code = 'XhVZiHLpMnJ' WHERE name = E'Netherlands';
UPDATE countries SET dhis2_code = 'SFnJXKHtNPT' WHERE name = E'New Caledonia';
UPDATE countries SET dhis2_code = 'NbSAL47OfTk' WHERE name = E'New Zealand';
UPDATE countries SET dhis2_code = 'G9i0iHpkYbp' WHERE name = E'Nicaragua';
UPDATE countries SET dhis2_code = 'isQUPKHcs6X' WHERE name = E'Niger';
UPDATE countries SET dhis2_code = 'i6mNzSoi00T' WHERE name = E'Nigeria';
UPDATE countries SET dhis2_code = 'fsojvbtJaQ9' WHERE name = E'Niue';
UPDATE countries SET dhis2_code = 'CHVoLfGmFbt' WHERE name = E'Norfolk Island';
UPDATE countries SET dhis2_code = 'DnKpeOCqfDu' WHERE name = E'Northern Mariana Islands';
UPDATE countries SET dhis2_code = 'abXMcNMfUHW' WHERE name = E'Norway';
UPDATE countries SET dhis2_code = 'KCS77S1n8yE' WHERE name = E'Oman';
UPDATE countries SET dhis2_code = 'Vd3efHrokOx' WHERE name = E'Pakistan';
UPDATE countries SET dhis2_code = 'nuJCiz6sWMs' WHERE name = E'Palau';
UPDATE countries SET dhis2_code = 'PSXaRzhAoO5' WHERE name = E'Palestine, State of';
UPDATE countries SET dhis2_code = 'Z4UIfFiFuMC' WHERE name = E'Panama';
UPDATE countries SET dhis2_code = 'y5Edd8OyiIS' WHERE name = E'Papua New Guinea';
UPDATE countries SET dhis2_code = 'JtLlBt8z3Th' WHERE name = E'Paraguay';
UPDATE countries SET dhis2_code = 'u0Iy4qXUpGx' WHERE name = E'Peru';
UPDATE countries SET dhis2_code = 'Hn8n03RTQoy' WHERE name = E'Philippines';
UPDATE countries SET dhis2_code = 'UH9iMU8RCbR' WHERE name = E'Pitcairn';
UPDATE countries SET dhis2_code = 'TgDFVQK8poQ' WHERE name = E'Poland';
UPDATE countries SET dhis2_code = 'fJGUZnvCg0m' WHERE name = E'Portugal';
UPDATE countries SET dhis2_code = 'pMggNgUQ24t' WHERE name = E'Puerto Rico';
UPDATE countries SET dhis2_code = 'YBnIVZiENSl' WHERE name = E'Qatar';
UPDATE countries SET dhis2_code = 'dyHaYgO8uRD' WHERE name = E'Reunion';
UPDATE countries SET dhis2_code = 'fDggEkf3s9Q' WHERE name = E'Romania';
UPDATE countries SET dhis2_code = 'Vh7og15xjfI' WHERE name = E'Russian Federation';
UPDATE countries SET dhis2_code = 'XFtEiGSEM5K' WHERE name = E'Rwanda';
UPDATE countries SET dhis2_code = 'TlWg479ykNG' WHERE name = E'Saint Barthalemy';
UPDATE countries SET dhis2_code = 'AbZ1Ahy2uzF' WHERE name = E'Saint Helena, Ascension and Tristan da Cunha';
UPDATE countries SET dhis2_code = 'Vx5yJqEFdiG' WHERE name = E'Saint Kitts and Nevis';
UPDATE countries SET dhis2_code = 'oJtdF4dJlKR' WHERE name = E'Saint Lucia';
UPDATE countries SET dhis2_code = 'Fjs0ekdnQp4' WHERE name = E'Saint Martin (French part)';
UPDATE countries SET dhis2_code = 'cuBbK1kGxQG' WHERE name = E'Saint Pierre and Miquelon';
UPDATE countries SET dhis2_code = 'CgCPhepq1T0' WHERE name = E'Saint Vincent and the Grenadines';
UPDATE countries SET dhis2_code = 'OiiQDTwRhiJ' WHERE name = E'Samoa';
UPDATE countries SET dhis2_code = 'kgx4yTXnCm5' WHERE name = E'San Marino';
UPDATE countries SET dhis2_code = 'ot9j1RhdTxJ' WHERE name = E'Sao Tome and Principe';
UPDATE countries SET dhis2_code = 'K2Z3GIjbpfy' WHERE name = E'Saudi Arabia';
UPDATE countries SET dhis2_code = 'IjeQQN6i6oB' WHERE name = E'Senegal';
UPDATE countries SET dhis2_code = 'mwQoRreFhS4' WHERE name = E'Serbia';
UPDATE countries SET dhis2_code = 'nslF0rp6DYP' WHERE name = E'Seychelles';
UPDATE countries SET dhis2_code = 'm5Mzp8gH9SE' WHERE name = E'Sierra Leone';
UPDATE countries SET dhis2_code = 'pGtXTzwNgYJ' WHERE name = E'Singapore';
UPDATE countries SET dhis2_code = 'wU06ZppIUrr' WHERE name = E'Sint Maarten (Dutch part)';
UPDATE countries SET dhis2_code = 'SVkuqbtbwkn' WHERE name = E'Slovakia';
UPDATE countries SET dhis2_code = 'tgZNiP0av9R' WHERE name = E'Slovenia';
UPDATE countries SET dhis2_code = 'C6mh8woRILR' WHERE name = E'Solomon Islands';
UPDATE countries SET dhis2_code = 'XUAgsUvnd9D' WHERE name = E'Somalia';
UPDATE countries SET dhis2_code = 'ybi90nX7jIG' WHERE name = E'South Africa';
UPDATE countries SET dhis2_code = 'xscRY8jGm4I' WHERE name = E'South Georgia and the South Sandwich Islands';
UPDATE countries SET dhis2_code = 'nucHGYLnDym' WHERE name = E'South Sudan';
UPDATE countries SET dhis2_code = 'AWCr3B2Ec6K' WHERE name = E'Spain';
UPDATE countries SET dhis2_code = 'vVm2PrIRCZb' WHERE name = E'Sri Lanka';
UPDATE countries SET dhis2_code = 'tmChdi1uORn' WHERE name = E'Sudan';
UPDATE countries SET dhis2_code = 'dsiiSBdkIOV' WHERE name = E'Suriname';
UPDATE countries SET dhis2_code = 'HvsdUX9XzqA' WHERE name = E'Svalbard and Jan Mayen';
UPDATE countries SET dhis2_code = 'LSa01WRIEoa' WHERE name = E'Swaziland';
UPDATE countries SET dhis2_code = 'BkyPw8ckTNY' WHERE name = E'Sweden';
UPDATE countries SET dhis2_code = 'TtTR0Yl2wu4' WHERE name = E'Switzerland';
UPDATE countries SET dhis2_code = 'rWZk1zIRhxd' WHERE name = E'Syrian Arab Republic';
UPDATE countries SET dhis2_code = 'YiWILyGjKnW' WHERE name = E'Taiwan, Province of China';
UPDATE countries SET dhis2_code = 'z3ciloHD9PX' WHERE name = E'Tajikistan';
UPDATE countries SET dhis2_code = 'EfbDHbL0WVR' WHERE name = E'Tanzania, United Republic of';
UPDATE countries SET dhis2_code = 'NgOETSb20pt' WHERE name = E'Thailand';
UPDATE countries SET dhis2_code = 'GHlYciOJcc3' WHERE name = E'Timor-Leste';
UPDATE countries SET dhis2_code = 'lxBYLgAGHyI' WHERE name = E'Togo';
UPDATE countries SET dhis2_code = 'ysx0MV7RW2X' WHERE name = E'Tokelau';
UPDATE countries SET dhis2_code = 'E8gQhClNFbP' WHERE name = E'Tonga';
UPDATE countries SET dhis2_code = 'vpOUqs1VdKL' WHERE name = E'Trinidad and Tobago';
UPDATE countries SET dhis2_code = 'f5ZqqjsV2PJ' WHERE name = E'Tunisia';
UPDATE countries SET dhis2_code = 'cpSzNk48yTR' WHERE name = E'Turkey';
UPDATE countries SET dhis2_code = 'ziovQhoHqXQ' WHERE name = E'Turkmenistan';
UPDATE countries SET dhis2_code = 'PxkPTw9fbIk' WHERE name = E'Turks and Caicos Islands';
UPDATE countries SET dhis2_code = 'RuqZKue3rFr' WHERE name = E'Tuvalu';
UPDATE countries SET dhis2_code = 'clThxUwFWOz' WHERE name = E'Uganda';
UPDATE countries SET dhis2_code = 'N1cS8AIDi1q' WHERE name = E'Ukraine';
UPDATE countries SET dhis2_code = 'PDxzpx08WBj' WHERE name = E'United Arab Emirates';
UPDATE countries SET dhis2_code = 'QBbuw7ibNxz' WHERE name = E'United Kingdom of Great Britain and Northern Ireland';
UPDATE countries SET dhis2_code = 'slJul3ojjA4' WHERE name = E'United States Minor Outlying Islands';
UPDATE countries SET dhis2_code = 'rFyxYwKsUHn' WHERE name = E'United States of America';
UPDATE countries SET dhis2_code = 'J6NKBEYkEIX' WHERE name = E'Uruguay';
UPDATE countries SET dhis2_code = 'MZtPirsiobx' WHERE name = E'Uzbekistan';
UPDATE countries SET dhis2_code = 'zz44ZJwE4BC' WHERE name = E'Vanuatu';
UPDATE countries SET dhis2_code = 'aO1V8Km6tIa' WHERE name = E'Venezuela (Bolivarian Republic of)';
UPDATE countries SET dhis2_code = 'alllxGOxa3E' WHERE name = E'Viet Nam';
UPDATE countries SET dhis2_code = 'yKhE8gOOm3t' WHERE name = E'Virgin Islands (British)';
UPDATE countries SET dhis2_code = 'MmfxULjuTXH' WHERE name = E'Virgin Islands (U.S.)';
UPDATE countries SET dhis2_code = 'ctQxqa1n0Ki' WHERE name = E'Wallis and Futuna';
UPDATE countries SET dhis2_code = 'NdVZXFSvX7t' WHERE name = E'Western Sahara';
UPDATE countries SET dhis2_code = 'oJ7nxbnJtlz' WHERE name = E'Yemen';
UPDATE countries SET dhis2_code = 'SJm6VUYbovd' WHERE name = E'Zambia';
UPDATE countries SET dhis2_code = 'YULlOdKf9DK' WHERE name = E'Zimbabwe';
