INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Adramachako POE', 'LO58GMPGD6H', '/akV6429SUqu/BD3XaQ7cQAp/WcB3kLlgRTb/LO58GMPGD6H', 'WcB3kLlgRTb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Afogi POE', 'BfbBweh7Af3', '/akV6429SUqu/BD3XaQ7cQAp/W0kQBddyGyh/BfbBweh7Af3', 'W0kQBddyGyh');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Alakas POE', 'KeoDmfuEaML', '/akV6429SUqu/jdlbNUwJiKX/a8RHFdF4DXL/KeoDmfuEaML', 'a8RHFdF4DXL');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Amudat POE', 'YYo8GtTNHWF', '/akV6429SUqu/jdlbNUwJiKX/a8RHFdF4DXL/YYo8GtTNHWF', 'a8RHFdF4DXL');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Apiriti POE', 'TWfwWeAc5em', '/akV6429SUqu/SUvODYOcaVf/xy0M4HhjXtD/TWfwWeAc5em', 'xy0M4HhjXtD');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Arua Airport POE', 'JPK44GfoZuS', '/akV6429SUqu/BD3XaQ7cQAp/WcB3kLlgRTb/JPK44GfoZuS', 'WcB3kLlgRTb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Aweroluwi POE', 'Lvg45y5AGDU', '/akV6429SUqu/SUvODYOcaVf/xy0M4HhjXtD/Lvg45y5AGDU', 'xy0M4HhjXtD');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Birijaku POE', 'EjGffqn5bTU', '/akV6429SUqu/BD3XaQ7cQAp/iqsaGItA68C/EjGffqn5bTU', 'iqsaGItA68C');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Bugango POE', 'kyGQBIeEJ0y', '/akV6429SUqu/F1o6qBSx783/UaR7OHycj8c/kyGQBIeEJ0y', 'UaR7OHycj8c');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Buhuka POE', 'ksUZ6AmGFYl', '/akV6429SUqu/yx0ieyZNF0l/L5WBetpBpY3/ksUZ6AmGFYl', 'L5WBetpBpY3');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Bunagana POE', 'vCLRAwJAjHH', '/akV6429SUqu/G0rlphd2tcD/aPhSZRinfbg/vCLRAwJAjHH', 'aPhSZRinfbg');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Busanza POE', 'h6izhRxC4Ho', '/akV6429SUqu/G0rlphd2tcD/aPhSZRinfbg/h6izhRxC4Ho', 'aPhSZRinfbg');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Busia POE', 'Rb1I98ZhdmN', '/akV6429SUqu/QBPg7KKCeoA/lkuO79O6mRx/Rb1I98ZhdmN', 'lkuO79O6mRx');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Busunga POE', 'gbPOixjr12T', '/akV6429SUqu/JZhJ50nOirX/g8M1cWRJZV6/gbPOixjr12T', 'g8M1cWRJZV6');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Butiaba POE', 'PSDnFhkMqur', '/akV6429SUqu/yx0ieyZNF0l/xr8EMirOASp/PSDnFhkMqur', 'xr8EMirOASp');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Butogota POE', 'AmIF0vS2HR7', '/akV6429SUqu/G0rlphd2tcD/aphcy5JTnd6/AmIF0vS2HR7', 'aphcy5JTnd6');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Buvuma Ferry POE', 'ZBgxWlRnAlr', '/akV6429SUqu/Dl9WvtvDs5V/aZLZPPjqft0/ZBgxWlRnAlr', 'aZLZPPjqft0');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Cyanika POE', 'hvgYsK32CUE', '/akV6429SUqu/G0rlphd2tcD/aPhSZRinfbg/hvgYsK32CUE', 'aPhSZRinfbg');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Dei POE', 'Nmj3EpXwxRc', '/akV6429SUqu/BD3XaQ7cQAp/uqUyTPvQKII/Nmj3EpXwxRc', 'uqUyTPvQKII');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Elegu POE', 'ipKbFh5D6AB', '/akV6429SUqu/SUvODYOcaVf/C0RSe3EWBqU/ipKbFh5D6AB', 'C0RSe3EWBqU');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Entebbe Airport POE', 'YTr0VOD4rea', '/akV6429SUqu/IEU0FjDAhBP/aIahLLmtvgT/YTr0VOD4rea', 'aIahLLmtvgT');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Fridge POE', 'WtbRNaI8qZT', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/WtbRNaI8qZT', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Goli POE', 'gLsl6NU1l6p', '/akV6429SUqu/BD3XaQ7cQAp/Xjc0LDFa5gW/gLsl6NU1l6p', 'Xjc0LDFa5gW');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Hima Cement POE', 'RbCz0gLD2DH', '/akV6429SUqu/JZhJ50nOirX/aa8xVDzSpte/RbCz0gLD2DH', 'aa8xVDzSpte');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Ishasha POE', 'WJEgavFV2e8', '/akV6429SUqu/G0rlphd2tcD/aphcy5JTnd6/WJEgavFV2e8', 'aphcy5JTnd6');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Jinja POE', 'YwkO5rrqhSu', '/akV6429SUqu/Wd1lV9Qdj4o/aJR2ZxSH7g4/YwkO5rrqhSu', 'aJR2ZxSH7g4');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kaiso-Tonya POE', 'UisOCMpfQoe', '/akV6429SUqu/yx0ieyZNF0l/PJFtfCyp6Rb/UisOCMpfQoe', 'PJFtfCyp6Rb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kakira Airstrip POE', 'MhQ8oCslkQR', '/akV6429SUqu/Wd1lV9Qdj4o/aJR2ZxSH7g4/MhQ8oCslkQR', 'aJR2ZxSH7g4');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kamion POE', 'TZbBkZRebXl', '/akV6429SUqu/jdlbNUwJiKX/eOJUW6OGpc7/TZbBkZRebXl', 'eOJUW6OGpc7');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kamwezi POE', 'bDH5wXYh0nX', '/akV6429SUqu/G0rlphd2tcD/fsP0Wxie1UW/bDH5wXYh0nX', 'fsP0Wxie1UW');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kanara POE', 'JWTxEN238bd', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/JWTxEN238bd', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kasensero POE', 'jPElHbyX2go', '/akV6429SUqu/IEU0FjDAhBP/REJuxCmTwXG/jPElHbyX2go', 'REJuxCmTwXG');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Katanga POE', 'rAEgsxYnQs8', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/rAEgsxYnQs8', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Katosi Cape POE', 'Ms9DSCjfqW8', '/akV6429SUqu/Dl9WvtvDs5V/a0DfYpC2Rwl/Ms9DSCjfqW8', 'a0DfYpC2Rwl');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Katosi POE', 'pMsxDyqjb4k', '/akV6429SUqu/Dl9WvtvDs5V/a0DfYpC2Rwl/pMsxDyqjb4k', 'a0DfYpC2Rwl');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Katuna POE', 'MaThmStkNm2', '/akV6429SUqu/G0rlphd2tcD/zBIpPzKYFLp/MaThmStkNm2', 'zBIpPzKYFLp');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Katwe POE', 'qC1fObxT3vp', '/akV6429SUqu/JZhJ50nOirX/aa8xVDzSpte/qC1fObxT3vp', 'aa8xVDzSpte');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kayanja POE', 'c44oXsR3pC1', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/c44oXsR3pC1', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kayanzi POE', 'FQwp83f54BK', '/akV6429SUqu/JZhJ50nOirX/aa8xVDzSpte/FQwp83f54BK', 'aa8xVDzSpte');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kazinga PoE', 'DLziQkFaxNZ', '/akV6429SUqu/F1o6qBSx783/fS71jg1WYPk/DLziQkFaxNZ', 'fS71jg1WYPk');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kidepo Airstrip POE', 'FiIz0GbUWGX', '/akV6429SUqu/jdlbNUwJiKX/eOJUW6OGpc7/FiIz0GbUWGX', 'eOJUW6OGpc7');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kigungu POE', 'SN8Jm0o3fq4', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/SN8Jm0o3fq4', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kikagate POE', 'ncVXpL0h6fh', '/akV6429SUqu/F1o6qBSx783/UaR7OHycj8c/ncVXpL0h6fh', 'UaR7OHycj8c');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kikongo POE', 'SZ9MbaN5xDg', '/akV6429SUqu/Dl9WvtvDs5V/aZLZPPjqft0/SZ9MbaN5xDg', 'aZLZPPjqft0');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kimaka Airstrip POE', 'WHTf2NulQ0o', '/akV6429SUqu/Wd1lV9Qdj4o/aJR2ZxSH7g4/WHTf2NulQ0o', 'aJR2ZxSH7g4');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kisenyi PoE', 'TWwba6NODFV', '/akV6429SUqu/F1o6qBSx783/fS71jg1WYPk/TWwba6NODFV', 'fS71jg1WYPk');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kiyindi POE', 'd6Mf0DphU5j', '/akV6429SUqu/Dl9WvtvDs5V/x75Yh65MaUa/d6Mf0DphU5j', 'x75Yh65MaUa');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kokwochaku POE', 'Q2XZvOJ20wN', '/akV6429SUqu/jdlbNUwJiKX/a8RHFdF4DXL/Q2XZvOJ20wN', 'a8RHFdF4DXL');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kyebukube POE', 'Elye94vi3EI', '/akV6429SUqu/Dt6qdenPX1E/JIZDvNlIhXS/Elye94vi3EI', 'JIZDvNlIhXS');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kyeshero POE', 'Yj4N9dJ697R', '/akV6429SUqu/G0rlphd2tcD/aphcy5JTnd6/Yj4N9dJ697R', 'aphcy5JTnd6');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Kyetume POE', 'pk8xD5NXs4R', '/akV6429SUqu/Dl9WvtvDs5V/a0DfYpC2Rwl/pk8xD5NXs4R', 'a0DfYpC2Rwl');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Lia POE', 'iqdQZZux5pG', '/akV6429SUqu/BD3XaQ7cQAp/WcB3kLlgRTb/iqdQZZux5pG', 'WcB3kLlgRTb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Logiri POE', 'Yc31ewUROUB', '/akV6429SUqu/BD3XaQ7cQAp/WcB3kLlgRTb/Yc31ewUROUB', 'WcB3kLlgRTb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Lokitoinyala POE', 'ZEKJN0YaivX', '/akV6429SUqu/jdlbNUwJiKX/A9kRCvmn6Co/ZEKJN0YaivX', 'A9kRCvmn6Co');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Lolwe Island POE', 'aXQFhvNHYR3', '/akV6429SUqu/Wd1lV9Qdj4o/Ut0ysYGEipO/aXQFhvNHYR3', 'Ut0ysYGEipO');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Lubya Station POE', 'mJCtUv7GTl9', '/akV6429SUqu/Dl9WvtvDs5V/aZLZPPjqft0/mJCtUv7GTl9', 'aZLZPPjqft0');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Lwakhaka POE', 'ipVHJMR86ks', '/akV6429SUqu/Dt6qdenPX1E/TGzZPOmbgn8/ipVHJMR86ks', 'TGzZPOmbgn8');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Madi-Opei POE', 'tTAeSbXOaOj', '/akV6429SUqu/SUvODYOcaVf/xy0M4HhjXtD/tTAeSbXOaOj', 'xy0M4HhjXtD');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Malaba POE', 'tAN8bVxaZ0V', '/akV6429SUqu/QBPg7KKCeoA/KhT80mlwJ3Y/tAN8bVxaZ0V', 'KhT80mlwJ3Y');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Mirama Hills POE', 'eXIl50I2fI2', '/akV6429SUqu/F1o6qBSx783/hAoe9dhZh9V/eXIl50I2fI2', 'hAoe9dhZh9V');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Mpondwe POE', 'bPtIfbGkCDB', '/akV6429SUqu/JZhJ50nOirX/aa8xVDzSpte/bPtIfbGkCDB', 'aa8xVDzSpte');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Munyanga POE', 'DwszEmVJVHL', '/akV6429SUqu/G0rlphd2tcD/aphcy5JTnd6/DwszEmVJVHL', 'aphcy5JTnd6');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Mutukula POE', 'A4oE1TLf5Lb', '/akV6429SUqu/IEU0FjDAhBP/P8iz90eiIrW/A4oE1TLf5Lb', 'P8iz90eiIrW');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Nakabaat POE', 'UrzjUUjOD3F', '/akV6429SUqu/jdlbNUwJiKX/A9kRCvmn6Co/UrzjUUjOD3F', 'A9kRCvmn6Co');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Namanve Seclusion Point', 'BfW0x8SlVnk', '/akV6429SUqu/Dl9WvtvDs5V/a0DfYpC2Rwl/BfW0x8SlVnk', 'a0DfYpC2Rwl');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Ndaiga POE', 'FZgD0J54FbU', '/akV6429SUqu/JZhJ50nOirX/m77oR1YJESj/FZgD0J54FbU', 'm77oR1YJESj');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Ngomrom POE', 'rwCXL7xUtrz', '/akV6429SUqu/SUvODYOcaVf/xy0M4HhjXtD/rwCXL7xUtrz', 'xy0M4HhjXtD');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Nkata Station POE', 'mKIcKtPoH45', '/akV6429SUqu/Dl9WvtvDs5V/aZLZPPjqft0/mKIcKtPoH45', 'aZLZPPjqft0');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Nsonga POE', 'EYHBGlrtu2I', '/akV6429SUqu/yx0ieyZNF0l/L5WBetpBpY3/EYHBGlrtu2I', 'L5WBetpBpY3');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Ntoroko Main POE', 'Y0uXYl1fRTY', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/Y0uXYl1fRTY', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Opotpot POE', 'ac9MlbYmGPx', '/akV6429SUqu/jdlbNUwJiKX/Hmh5JQLls1d/ac9MlbYmGPx', 'Hmh5JQLls1d');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Oraba POE', 'YmhmKdYyRom', '/akV6429SUqu/BD3XaQ7cQAp/iqsaGItA68C/YmhmKdYyRom', 'iqsaGItA68C');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Padea POE', 'dzKzYkSzQ67', '/akV6429SUqu/BD3XaQ7cQAp/A4aGXEfdb8P/dzKzYkSzQ67', 'A4aGXEfdb8P');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Paidha POE', 'wXqG74nuQ6t', '/akV6429SUqu/BD3XaQ7cQAp/A4aGXEfdb8P/wXqG74nuQ6t', 'A4aGXEfdb8P');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Portbell POE', 'VFXzMXLMADk', '/akV6429SUqu/GIpyzaSuEgM/aXmBzv61LbM/VFXzMXLMADk', 'aXmBzv61LbM');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Runga POE', 's3FmygYATd4', '/akV6429SUqu/Dl9WvtvDs5V/x75Yh65MaUa/s3FmygYATd4', 'x75Yh65MaUa');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Rwangara POE', 'xiYBUqXD6pP', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/xiYBUqXD6pP', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Rwebisengo POE', 'cneiB3CiQKC', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/cneiB3CiQKC', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Rwenshama POE', 'jwxCvdvh2oX', '/akV6429SUqu/G0rlphd2tcD/tugqr4dY6wq/jwxCvdvh2oX', 'tugqr4dY6wq');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Sebagoro POE', 'xpwGYmcppDv', '/akV6429SUqu/yx0ieyZNF0l/PJFtfCyp6Rb/xpwGYmcppDv', 'PJFtfCyp6Rb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Senyi B POE', 'bQ9GQDYmU6H', '/akV6429SUqu/Dl9WvtvDs5V/x75Yh65MaUa/bQ9GQDYmU6H', 'x75Yh65MaUa');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Senyi POE', 'YbgvZgX5p8q', '/akV6429SUqu/Dl9WvtvDs5V/x75Yh65MaUa/YbgvZgX5p8q', 'x75Yh65MaUa');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Singulu Island POE', 'ziiqqBNY1dh', '/akV6429SUqu/Wd1lV9Qdj4o/gUaoj8Geuao/ziiqqBNY1dh', 'gUaoj8Geuao');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Suam POE', 'FJjGJV7qJkU', '/akV6429SUqu/Dt6qdenPX1E/e8m9ZYMRoeR/FJjGJV7qJkU', 'e8m9ZYMRoeR');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Transami POE', 'yuVJGlxuYJm', '/akV6429SUqu/JZhJ50nOirX/z8D9ER36EKN/yuVJGlxuYJm', 'z8D9ER36EKN');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Vurra POE', 'fZRpGGvN6y4', '/akV6429SUqu/BD3XaQ7cQAp/WcB3kLlgRTb/fZRpGGvN6y4', 'WcB3kLlgRTb');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Wakawaka POE', 'hPFgpzfq5dO', '/akV6429SUqu/Wd1lV9Qdj4o/gUaoj8Geuao/hPFgpzfq5dO', 'gUaoj8Geuao');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Waligo POE', 'fSAo62Tlmly', '/akV6429SUqu/SUvODYOcaVf/xy0M4HhjXtD/fSAo62Tlmly', 'xy0M4HhjXtD');
INSERT INTO ports (name,dhis2_code, dhis2_path, dhis2_parent) VALUES('Wanseko POE', 'P2mETI3Zy95', '/akV6429SUqu/yx0ieyZNF0l/CQTmrrriwOq/P2mETI3Zy95', 'CQTmrrriwOq');
